# Generated by Django 4.2.6 on 2023-10-05 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0003_user_alter_note_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Owner',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='user',
            new_name='owner',
        ),
    ]
