# Generated by Django 4.2.6 on 2023-10-06 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0006_owner_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
